export const weatherData = [
  {
    day: '월',
    date: '4.08',
    morning: '0%',
    afternoon: '0%',
    lowest: '16°',
    highest: '17°',
    today: false,
  },
  {
    day: '화',
    date: '4.09',
    morning: '55%',
    afternoon: '75%',
    lowest: '15°',
    highest: '18°',
    today: true,
  },
  {
    day: '수',
    date: '4.10',
    morning: '65%',
    afternoon: '78%',
    lowest: '14°',
    highest: '19°',
    today: false,
  },
  {
    day: '목',
    date: '4.11',
    morning: '62%',
    afternoon: '82%',
    lowest: '16°',
    highest: '20°',
    today: false,
  },
  {
    day: '금',
    date: '4.12',
    morning: '58%',
    afternoon: '79%',
    lowest: '15°',
    highest: '18°',
    today: false,
  },
  {
    day: '토',
    date: '4.13',
    morning: '63%',
    afternoon: '81%',
    lowest: '17°',
    highest: '21°',
    today: false,
  },
  {
    day: '일',
    date: '4.14',
    morning: '59%',
    afternoon: '0%',
    lowest: '16°',
    highest: '19°',
    today: false,
  },
];
